services:
  app:
    image: 049705857334.dkr.ecr.eu-north-1.amazonaws.com/coursera/cumulative-task:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
   